### ISSUE TITLE
Remote device connection errors?

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_joint-interface#1]
On Linux system, after compiling the files, and type hereinafter and the errors occurred.
`$ yarpmotorgui`
![image](https://user-images.githubusercontent.com/55526431/69108872-56389e00-0ab9-11ea-9df1-6abc9c4583db.png)
`$./tutorial_joint-interface-position `
![image](https://user-images.githubusercontent.com/55526431/69108885-5df84280-0ab9-11ea-968f-dc0b6923d3af.png)
Also, I test it on the Linux system and similar errors occurred.

What are the meanings of remote device errors?

In addition, it seems that the tutorial link of Position Control, Velocity Control is invalid.

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

In order to launch the `yarpmotorgui` along with the simulated robot, you have to type the follwing command:
```sh
$ yarpmotorgui --robot icubSim
```

The `README.md` file has been updated accordingly. Thanks for reporting.
